services:
  worker:
    depends_on:
      # - postgres # Uncomment if want to direct connection to postgres
      - fishsense-api
    build:
      context: .
      dockerfile: Dockerfile.develop
    command: tail -f /dev/null
    volumes:
      - .:/home/ubuntu
    restart: none
    networks:
      - default

  # Uncomment if want to direct connection to postgres
  # postgres:
  #   image: postgres:16.4
  #   restart: always
  #   shm_size: 128 mb
  #   environment:
  #     POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
  #   volumes:
  #     - ./pg_volumes/data/:/var/lib/postgresql/data/:rw
  #     - ./pg_volumes/config/:/etc/postgresql/:ro
  #     - ./pg_volumes/scripts/:/docker-entrypoint-initdb.d/:ro
  #   secrets:
  #     - postgres_admin_password
  #   command: --config_file=/etc/postgresql/postgres.conf
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - default
  
  fishsense-api:
    image: fishsense-api:develop
    build:
      context: ../fishsense-api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - E4EFS_DOCKER=true
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_admin_password
    volumes:
      - ../fishsense-api/settings.toml:/e4efs/config/settings.toml:ro
      - ../fishsense-api/.secrets.toml:/e4efs/config/.secrets.toml:ro
    secrets:
      - postgres_admin_password
    networks:
      - default

secrets:
  postgres_admin_password: 
    file: .secrets/postgres_admin_password.txt

networks:
  default:
    name: fishsense-api-workflow-worker_default