[tool.poetry]
name = "fishsense-lite"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyFishSense = { git = "https://github.com/UCSD-E4E/pyFishSense.git", branch = "feature/pyfishsense" }
bom-common = {git = "https://github.com/UCSD-E4E/bom-common", rev = "main"}
matplotlib = "^3.8.0"
pandas = "^2.1.1"
ray = "^2.9.3"

[tool.poetry.dev-dependencies]
black = "^23.12.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
