[tool.poetry]
name = "fishsense-lite"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyFishSenseDev = { git = "https://github.com/UCSD-E4E/pyFishSenseDev", branch = "main" }
pyFishSense = { git = "https://github.com/UCSD-E4E/pyFishSense", branch = "main" }
fishsense-common = {git = "https://github.com/UCSD-E4E/fishsense-common", rev = "main"}
matplotlib = "^3.8.0"
pandas = "^2.1.1"
ray = "^2.9.3"
gitpython = "^3.1.42"
backoff = "^2.2.1"
xlrd = "^2.0.1"
seaborn = "^0.13.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"
black = "^24.3.0"
pylint = "^3.2.0"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu124"
priority = "supplemental"

[tool.poetry.scripts]
fsl = "fishsense_lite.run:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
