[project]
name = "fishsense-lite"
version = "1.1.1"
description = ""
authors = [
    {name = "Christopher L. Crutchfield",email = "ccrutchf@ucsd.edu"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "matplotlib (>=3.10.0,<4.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "ray[default] (>=2.46.0,<3.0.0)",
    "backoff (>=2.2.1,<3.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "torch (>=2.6.0,<3.0.0)",
    "torchvision (>=0.21.0,<0.22.0)",
    "gitpython (>=3.1.44,<4.0.0)",
    "xlrd (>=2.0.1,<3.0.0)",
    "pyaqua3ddev @ git+https://github.com/UCSD-E4E/pyAqua3dDev.git",
    "pyfishsense @ git+https://github.com/UCSD-E4E/pyFishSense.git",
    "fishsense-common @ git+https://github.com/UCSD-E4E/fishsense-common.git",
    "pyfishsensedev @ git+https://github.com/UCSD-E4E/pyFishSenseDev.git",
    "psycopg[binary] (>=3.2.6,<4.0.0)",
    "fsspec (>=2025.5.0,<2026.0.0)",
    "universal-pathlib (>=0.2.6,<0.3.0)",
    "smbprotocol (>=1.15.0,<2.0.0)",
]

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
black = "^25.1.0"
pylint = "^3.3.4"
ipywidgets = "^8.1.5"
python-semantic-release = "^10.0.2"

[tool.poetry.scripts]
fsl = "fishsense_lite.run:main"

[tool.semantic_release]
version_variables = ["fishsense_lite/__init__.py:__version__"]
version_toml = [
    "pyproject.toml:project.version",
]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false
prerelease_token = "rc"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
