[project]
name = "fishsense-lite"
version = "0.1.0"
description = ""
authors = [
    {name = "Christopher L. Crutchfield",email = "ccrutchf@ucsd.edu"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "matplotlib (>=3.10.0,<4.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "ray (>=2.42.0,<3.0.0)",
    "backoff (>=2.2.1,<3.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "torch (>=2.6.0,<3.0.0)",
    "torchvision (>=0.21.0,<0.22.0)",
    "gitpython (>=3.1.44,<4.0.0)",
    "xlrd (>=2.0.1,<3.0.0)",
    "pyaqua3ddev @ git+https://github.com/UCSD-E4E/pyAqua3dDev.git",
    "pyfishsense @ git+https://github.com/UCSD-E4E/pyFishSense.git",
    "fishsense-common @ git+https://github.com/UCSD-E4E/fishsense-common.git",
    "pyfishsensedev @ git+https://github.com/UCSD-E4E/pyFishSenseDev.git",
]

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
black = "^25.1.0"
pylint = "^3.3.4"
ipywidgets = "^8.1.5"

[tool.poetry.scripts]
fsl = "fishsense_lite.run:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
