[tool.poetry]
name = "fishsense-lite"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
fishsense-lite-python-pipeline = { git = "https://github.com/UCSD-E4E/fishsense-lite-python-pipeline.git", branch = "main" }
matplotlib = "^3.8.0"
pandas = "^2.1.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
