#! /bin/bash

docker run --rm -it --gpus=all -e NVIDIA_DRIVER_CAPABILITIES=all -e PSQL_PASSWORD=$PSQL_PASSWORD -v /:/home/ubuntu/root -v ~/mnt/:/home/ubuntu/mnt/ -v ~/Results/:/home/ubuntu/Results -v ~/Configs:/home/ubuntu/Configs --shm-size=10.24gb `whoami`/fishsense-lite
#docker run --rm -it -e NVIDIA_DRIVER_CAPABILITIES=all -v ~/mnt/:/home/ubuntu/mnt/ -v ~/Results/:/home/ubuntu/Results -v ~/Configs:/home/ubuntu/Configs --shm-size=10.24gb `whoami`/fishsense-lite
