# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, constr


class BodySetNotesApiV1DivesDiveIdNotesPut(BaseModel):
    notes: str | None = Field(None, title='Notes')


class CalibrationCandidate(BaseModel):
    """
    A dive whose laser-line fingerprint matches the target's, so its
    `LaserExtrinsics` is a borrow candidate. Read-only response DTO.
    """

    dive_id: int = Field(..., title='Dive Id')
    name: str | None = Field(..., title='Name')
    camera_id: int | None = Field(..., title='Camera Id')
    dive_datetime: AwareDatetime = Field(..., title='Dive Datetime')
    laser_extrinsics_id: int = Field(..., title='Laser Extrinsics Id')
    line_angle_deg: float = Field(..., title='Line Angle Deg')
    line_offset_px: float = Field(..., title='Line Offset Px')
    line_confidence: float = Field(..., title='Line Confidence')
    residual_std: float = Field(..., title='Residual Std')
    days_apart: float = Field(..., title='Days Apart')


class Camera(BaseModel):
    """
    Model representing a camera.
    """

    id: int | None = Field(None, title='Id')
    serial_number: str = Field(..., title='Serial Number')
    name: str = Field(..., title='Name')


class CameraIntrinsics(BaseModel):
    """
    Model representing camera intrinsics.
    """

    id: int | None = Field(None, title='Id')
    camera_matrix: list[list[float]] | None = Field(None, title='Camera Matrix')
    distortion_coefficients: list[float] | None = Field(
        None, title='Distortion Coefficients'
    )
    camera_id: int | None = Field(None, title='Camera Id')


class DataSource(Enum):
    """
    Enumeration representing data source types.
    """

    PREDICTION = 'PREDICTION'
    LABEL_STUDIO = 'LABEL_STUDIO'


class DiveFrameClusterJson(BaseModel):
    """
    Pydantic model for serializing DiveFrameCluster data.
    """

    id: int | None = Field(..., title='Id')
    image_ids: list[int] = Field(..., title='Image Ids')
    data_source: DataSource
    updated_at: AwareDatetime | None = Field(..., title='Updated At')
    dive_id: int | None = Field(..., title='Dive Id')
    fish_id: int | None = Field(..., title='Fish Id')


class DiveLaserLine(BaseModel):
    """
    A dive's fitted 2D laser line `a*x + b*y + c = 0` plus fit-quality metrics.

    One row per dive (`uq_diveslaserline_dive_id`); `put_dive_laser_line`
    upserts on `dive_id`. `camera_id` / `dive_datetime` are NOT duplicated here
    — consumers join `Dive`. Same NULL-safe `server_default` pattern as
    LaserExtrinsics so a row can never be inserted with a NULL timestamp.
    """

    id: int | None = Field(None, title='Id')
    dive_id: int | None = Field(None, title='Dive Id')
    a: float = Field(..., title='A')
    b: float = Field(..., title='B')
    c: float = Field(..., title='C')
    n_points: int = Field(..., title='N Points')
    inlier_count: int = Field(..., title='Inlier Count')
    inlier_fraction: float = Field(..., title='Inlier Fraction')
    residual_std: float = Field(..., title='Residual Std')
    label_noise_mad: float = Field(..., title='Label Noise Mad')
    line_confidence: float = Field(..., title='Line Confidence')
    fitted_at: AwareDatetime | None = Field(None, title='Fitted At')


class DiveSlate(BaseModel):
    """
    Model representing a dive slate.
    """

    id: int | None = Field(None, title='Id')
    name: constr(max_length=100) = Field(..., title='Name')
    dpi: int | None = Field(None, title='Dpi')
    path: constr(max_length=255) = Field(..., title='Path')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    reference_points: list[list] | None = Field(None, title='Reference Points')


class DiveSlateLabel(BaseModel):
    """
    Model representing slate labels.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    upside_down: bool | None = Field(None, title='Upside Down')
    reference_points: list[list] | None = Field(None, title='Reference Points')
    slate_rectangle: list[list] | None = Field(None, title='Slate Rectangle')
    skipped_points: list[int] | None = Field(None, title='Skipped Points')
    image_url: str | None = Field(None, title='Image Url')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    completed: bool | None = Field(False, title='Completed')
    superseded: bool | None = Field(False, title='Superseded')
    needs_reprocess: bool | None = Field(False, title='Needs Reprocess')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class Fish(BaseModel):
    """
    Fish model representing a fish in the database.
    """

    id: int | None = Field(None, title='Id')
    name: str | None = Field(None, title='Name')
    species_id: int | None = Field(None, title='Species Id')


class HeadTailLabel(BaseModel):
    """
    Model representing a head-tail label.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    head_x: float | None = Field(None, title='Head X')
    head_y: float | None = Field(None, title='Head Y')
    tail_x: float | None = Field(None, title='Tail X')
    tail_y: float | None = Field(None, title='Tail Y')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    superseded: bool | None = Field(False, title='Superseded')
    completed: bool | None = Field(False, title='Completed')
    needs_reprocess: bool | None = Field(False, title='Needs Reprocess')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class Image(BaseModel):
    """
    Model representing an image.
    """

    id: int | None = Field(None, title='Id')
    path: constr(max_length=255) = Field(..., title='Path')
    taken_datetime: AwareDatetime | None = Field(None, title='Taken Datetime')
    checksum: constr(max_length=32) = Field(..., title='Checksum')
    is_canonical: bool | None = Field(False, title='Is Canonical')
    dive_id: int | None = Field(None, title='Dive Id')
    camera_id: int | None = Field(None, title='Camera Id')


class LabelStudioSyncCursor(BaseModel):
    """
    Per-(kind, project) high-water mark for Label Studio sync.
    """

    id: int | None = Field(None, title='Id')
    kind: str = Field(..., title='Kind')
    label_studio_project_id: int = Field(..., title='Label Studio Project Id')
    last_synced_at: AwareDatetime | None = Field(None, title='Last Synced At')


class LaserDepth(BaseModel):
    """
    The distance to an image's laser dot, in metres. One row per image —
    a recompute upserts on the natural key.
    """

    id: int | None = Field(None, title='Id')
    depth_m: float = Field(..., title='Depth M')
    range_m: float | None = Field(None, title='Range M')
    residual_m: float | None = Field(None, title='Residual M')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    image_id: int | None = Field(None, title='Image Id')
    laser_label_id: int | None = Field(None, title='Laser Label Id')
    laser_extrinsics_id: int | None = Field(None, title='Laser Extrinsics Id')


class LaserExtrinsics(BaseModel):
    """
    Laser extrinsics model representing laser calibration data in the database.

    One row per dive (`uq_laserextrinsics_dive_id`): calibration is a per-dive
    property, `put_laser_extrinsics_for_dive` upserts on `dive_id`, and no
    consumer reads a history of extrinsics — reads take the single row (or borrow
    a sibling's via `Dive.calibration_dive_id`). `created_at` carries a
    `server_default=now()` so a row can never be inserted with a NULL timestamp
    (which broke the latest-wins read: Postgres sorts NULLs first under DESC).
    """

    id: int | None = Field(None, title='Id')
    laser_position: list[float] | None = Field(None, title='Laser Position')
    laser_axis: list[float] | None = Field(None, title='Laser Axis')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    dive_id: int | None = Field(None, title='Dive Id')
    camera_id: int | None = Field(None, title='Camera Id')


class LaserLabel(BaseModel):
    """
    Model representing a laser label.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    x: float | None = Field(None, title='X')
    y: float | None = Field(None, title='Y')
    label: str | None = Field(None, title='Label')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    superseded: bool | None = Field(False, title='Superseded')
    completed: bool | None = Field(False, title='Completed')
    needs_reprocess: bool | None = Field(False, title='Needs Reprocess')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class LaserPrediction(BaseModel):
    """
    A model-predicted laser dot, in rectified-image pixels (the space
    labelers place `LaserLabel.x/y`). One row per image — re-prediction
    upserts on the natural key.
    """

    id: int | None = Field(None, title='Id')
    x: float | None = Field(None, title='X')
    y: float | None = Field(None, title='Y')
    confidence: float | None = Field(0.0, title='Confidence')
    width: int | None = Field(None, title='Width')
    height: int | None = Field(None, title='Height')
    color: str | None = Field(None, title='Color')
    color_margin: float | None = Field(None, title='Color Margin')
    rejected_out_of_region: bool | None = Field(False, title='Rejected Out Of Region')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    image_id: int | None = Field(None, title='Image Id')


class Measurement(BaseModel):
    """
    Measurement model representing fish measurements in the database.
    """

    id: int | None = Field(None, title='Id')
    length_m: float | None = Field(None, title='Length M')
    image_id: int | None = Field(None, title='Image Id')
    fish_id: int | None = Field(None, title='Fish Id')
    laser_extrinsics_id: int | None = Field(None, title='Laser Extrinsics Id')


class Priority(Enum):
    """
    Enumeration for priority levels.
    """

    LOW = 'LOW'
    HIGH = 'HIGH'
    NONE = 'NONE'


class SlatePrediction(BaseModel):
    """
    A model-predicted slate board for one image. One row per image —
    re-prediction upserts on the natural key.

    `reference_points` are in rectified-photo pixels (the space labelers place
    `DiveSlateLabel.reference_points` after the composite panel offset is
    stripped), or None when the estimate was rejected. `rejected_reason` records
    why nothing was seeded (`unsupported_slate_family` / `no_board` /
    `low_confidence` / `points_off_canvas`) for seed-rate monitoring.
    """

    id: int | None = Field(None, title='Id')
    reference_points: list[list[float]] | None = Field(None, title='Reference Points')
    confidence: float | None = Field(0.0, title='Confidence')
    rejected_reason: str | None = Field(None, title='Rejected Reason')
    width: int | None = Field(None, title='Width')
    height: int | None = Field(None, title='Height')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    image_id: int | None = Field(None, title='Image Id')


class Species(BaseModel):
    """
    Species model representing a fish species in the database.
    """

    id: int | None = Field(None, title='Id')
    scientific_name: str | None = Field(None, title='Scientific Name')
    common_name: str | None = Field(None, title='Common Name')


class SpeciesLabel(BaseModel):
    """
    Model representing a species label.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    image_url: str | None = Field(None, title='Image Url')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    completed: bool | None = Field(False, title='Completed')
    superseded: bool | None = Field(False, title='Superseded')
    needs_reprocess: bool | None = Field(False, title='Needs Reprocess')
    grouping: str | None = Field(None, title='Grouping')
    top_three_photos_of_group: bool | None = Field(
        None, title='Top Three Photos Of Group'
    )
    slate_upside_down: bool | None = Field(None, title='Slate Upside Down')
    laser_x: float | None = Field(None, title='Laser X')
    laser_y: float | None = Field(None, title='Laser Y')
    laser_label: str | None = Field(None, title='Laser Label')
    content_of_image: str | None = Field(None, title='Content Of Image')
    fish_measurable_category: str | None = Field(None, title='Fish Measurable Category')
    fish_angle_category: str | None = Field(None, title='Fish Angle Category')
    fish_curved_category: str | None = Field(None, title='Fish Curved Category')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class User(BaseModel):
    """
    Model representing a user.
    """

    id: int | None = Field(None, title='Id')
    label_studio_id: int | None = Field(None, title='Label Studio Id')
    email: constr(max_length=100) | None = Field(..., title='Email')
    first_name: constr(max_length=100) | None = Field(..., title='First Name')
    last_name: constr(max_length=100) | None = Field(..., title='Last Name')
    last_activity: AwareDatetime | None = Field(None, title='Last Activity')
    date_joined: AwareDatetime | None = Field(None, title='Date Joined')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class Dive(BaseModel):
    """
    Model representing a dive.
    """

    id: int | None = Field(None, title='Id')
    name: str | None = Field(None, title='Name')
    path: constr(max_length=255) = Field(..., title='Path')
    dive_datetime: AwareDatetime | None = Field(None, title='Dive Datetime')
    priority: Priority | None = 'LOW'
    flip_dive_slate: bool | None = Field(False, title='Flip Dive Slate')
    notes: str | None = Field(None, title='Notes')
    camera_id: int | None = Field(None, title='Camera Id')
    dive_slate_id: int | None = Field(None, title='Dive Slate Id')
    calibration_dive_id: int | None = Field(None, title='Calibration Dive Id')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
