# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, constr


class Camera(BaseModel):
    """
    Model representing a camera.
    """

    id: int | None = Field(None, title='Id')
    serial_number: str = Field(..., title='Serial Number')
    name: str = Field(..., title='Name')


class CameraIntrinsics(BaseModel):
    """
    Model representing camera intrinsics.
    """

    id: int | None = Field(None, title='Id')
    camera_matrix: list[list[float]] | None = Field(None, title='Camera Matrix')
    distortion_coefficients: list[float] | None = Field(
        None, title='Distortion Coefficients'
    )
    camera_id: int | None = Field(None, title='Camera Id')


class DataSource(Enum):
    """
    Enumeration representing data source types.
    """

    PREDICTION = 'PREDICTION'
    LABEL_STUDIO = 'LABEL_STUDIO'


class DiveFrameClusterJson(BaseModel):
    """
    Pydantic model for serializing DiveFrameCluster data.
    """

    id: int | None = Field(..., title='Id')
    image_ids: list[int] = Field(..., title='Image Ids')
    data_source: DataSource
    updated_at: AwareDatetime | None = Field(..., title='Updated At')
    dive_id: int | None = Field(..., title='Dive Id')
    fish_id: int | None = Field(..., title='Fish Id')


class DiveSlate(BaseModel):
    """
    Model representing a dive slate.
    """

    id: int | None = Field(None, title='Id')
    name: constr(max_length=100) = Field(..., title='Name')
    dpi: int | None = Field(None, title='Dpi')
    path: constr(max_length=255) = Field(..., title='Path')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    reference_points: list[list] | None = Field(None, title='Reference Points')


class DiveSlateLabel(BaseModel):
    """
    Model representing slate labels.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    upside_down: bool | None = Field(None, title='Upside Down')
    reference_points: list[list] | None = Field(None, title='Reference Points')
    slate_rectangle: list[list] | None = Field(None, title='Slate Rectangle')
    skipped_points: list[int] | None = Field(None, title='Skipped Points')
    image_url: str | None = Field(None, title='Image Url')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    completed: bool | None = Field(False, title='Completed')
    superseded: bool | None = Field(False, title='Superseded')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class Fish(BaseModel):
    """
    Fish model representing a fish in the database.
    """

    id: int | None = Field(None, title='Id')
    species_id: int | None = Field(None, title='Species Id')


class HeadTailLabel(BaseModel):
    """
    Model representing a head-tail label.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    head_x: float | None = Field(None, title='Head X')
    head_y: float | None = Field(None, title='Head Y')
    tail_x: float | None = Field(None, title='Tail X')
    tail_y: float | None = Field(None, title='Tail Y')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    superseded: bool | None = Field(False, title='Superseded')
    completed: bool | None = Field(False, title='Completed')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class Image(BaseModel):
    """
    Model representing an image.
    """

    id: int | None = Field(None, title='Id')
    path: constr(max_length=255) = Field(..., title='Path')
    taken_datetime: AwareDatetime | None = Field(None, title='Taken Datetime')
    checksum: constr(max_length=32) = Field(..., title='Checksum')
    is_canonical: bool | None = Field(False, title='Is Canonical')
    dive_id: int | None = Field(None, title='Dive Id')
    camera_id: int | None = Field(None, title='Camera Id')


class LabelStudioSyncCursor(BaseModel):
    """
    Per-(kind, project) high-water mark for Label Studio sync.
    """

    id: int | None = Field(None, title='Id')
    kind: str = Field(..., title='Kind')
    label_studio_project_id: int = Field(..., title='Label Studio Project Id')
    last_synced_at: AwareDatetime | None = Field(None, title='Last Synced At')


class LaserExtrinsics(BaseModel):
    """
    Laser extrinsics model representing laser calibration data in the database.
    """

    id: int | None = Field(None, title='Id')
    laser_position: list[float] | None = Field(None, title='Laser Position')
    laser_axis: list[float] | None = Field(None, title='Laser Axis')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    dive_id: int | None = Field(None, title='Dive Id')
    camera_id: int | None = Field(None, title='Camera Id')


class LaserLabel(BaseModel):
    """
    Model representing a laser label.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    x: float | None = Field(None, title='X')
    y: float | None = Field(None, title='Y')
    label: str | None = Field(None, title='Label')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    superseded: bool | None = Field(False, title='Superseded')
    completed: bool | None = Field(False, title='Completed')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class Measurement(BaseModel):
    """
    Measurement model representing fish measurements in the database.
    """

    id: int | None = Field(None, title='Id')
    length_m: float | None = Field(None, title='Length M')
    image_id: int | None = Field(None, title='Image Id')
    fish_id: int | None = Field(None, title='Fish Id')


class Priority(Enum):
    """
    Enumeration for priority levels.
    """

    LOW = 'LOW'
    HIGH = 'HIGH'


class Species(BaseModel):
    """
    Species model representing a fish species in the database.
    """

    id: int | None = Field(None, title='Id')
    scientific_name: str | None = Field(None, title='Scientific Name')
    common_name: str | None = Field(None, title='Common Name')


class SpeciesLabel(BaseModel):
    """
    Model representing a species label.
    """

    id: int | None = Field(None, title='Id')
    label_studio_task_id: int | None = Field(None, title='Label Studio Task Id')
    label_studio_project_id: int | None = Field(None, title='Label Studio Project Id')
    image_url: str | None = Field(None, title='Image Url')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    completed: bool | None = Field(False, title='Completed')
    superseded: bool | None = Field(False, title='Superseded')
    grouping: str | None = Field(None, title='Grouping')
    top_three_photos_of_group: bool | None = Field(
        None, title='Top Three Photos Of Group'
    )
    slate_upside_down: bool | None = Field(None, title='Slate Upside Down')
    laser_x: float | None = Field(None, title='Laser X')
    laser_y: float | None = Field(None, title='Laser Y')
    laser_label: str | None = Field(None, title='Laser Label')
    content_of_image: str | None = Field(None, title='Content Of Image')
    fish_measurable_category: str | None = Field(None, title='Fish Measurable Category')
    fish_angle_category: str | None = Field(None, title='Fish Angle Category')
    fish_curved_category: str | None = Field(None, title='Fish Curved Category')
    label_studio_json: dict[str, Any] | None = Field(None, title='Label Studio Json')
    image_id: int | None = Field(None, title='Image Id')
    user_id: int | None = Field(None, title='User Id')


class User(BaseModel):
    """
    Model representing a user.
    """

    id: int | None = Field(None, title='Id')
    label_studio_id: int | None = Field(None, title='Label Studio Id')
    email: constr(max_length=100) | None = Field(..., title='Email')
    first_name: constr(max_length=100) | None = Field(..., title='First Name')
    last_name: constr(max_length=100) | None = Field(..., title='Last Name')
    last_activity: AwareDatetime | None = Field(None, title='Last Activity')
    date_joined: AwareDatetime | None = Field(None, title='Date Joined')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class Dive(BaseModel):
    """
    Model representing a dive.
    """

    id: int | None = Field(None, title='Id')
    name: str | None = Field(None, title='Name')
    path: constr(max_length=255) = Field(..., title='Path')
    dive_datetime: AwareDatetime | None = Field(None, title='Dive Datetime')
    priority: Priority | None = 'LOW'
    flip_dive_slate: bool | None = Field(False, title='Flip Dive Slate')
    camera_id: int | None = Field(None, title='Camera Id')
    dive_slate_id: int | None = Field(None, title='Dive Slate Id')
    calibration_dive_id: int | None = Field(None, title='Calibration Dive Id')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
