"""add dive frame group

Revision ID: 3f9de863fb12
Revises: 72af359854fa
Create Date: 2025-09-15 02:11:00.452317

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9de863fb12'
down_revision: Union[str, Sequence[str], None] = '72af359854fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diveframegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diveframegroupimagemapping',
    sa.Column('dive_frame_group_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dive_frame_group_id'], ['diveframegroup.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('dive_frame_group_id', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diveframegroupimagemapping')
    op.drop_table('diveframegroup')
    # ### end Alembic commands ###
