"""add additional properties to dive slate labels

Revision ID: 0235b306ba14
Revises: 1f4ea39106fc
Create Date: 2025-11-23 19:56:36.626350

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0235b306ba14'
down_revision: Union[str, Sequence[str], None] = '1f4ea39106fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveslatelabel', sa.Column('upside_down', sa.Boolean(), nullable=True))
    op.add_column('diveslatelabel', sa.Column('reference_points', sa.JSON(), nullable=True))
    op.add_column('diveslatelabel', sa.Column('slate_rectangle', sa.JSON(), nullable=True))
    op.add_column('diveslatelabel', sa.Column('skipped_points', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diveslatelabel', 'skipped_points')
    op.drop_column('diveslatelabel', 'slate_rectangle')
    op.drop_column('diveslatelabel', 'reference_points')
    op.drop_column('diveslatelabel', 'upside_down')
    # ### end Alembic commands ###
