"""add superseded to headtail label

Revision ID: 06886d4ca175
Revises: 788e855b5474
Create Date: 2025-11-22 20:17:51.622461

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06886d4ca175'
down_revision: Union[str, Sequence[str], None] = '788e855b5474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headtaillabel', sa.Column('superseded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headtaillabel', 'superseded')
    # ### end Alembic commands ###
