"""add label studio project id to species label

Revision ID: 0771a69e2895
Revises: 4cf2f0d88592
Create Date: 2025-11-09 14:07:55.933893

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0771a69e2895'
down_revision: Union[str, Sequence[str], None] = '4cf2f0d88592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive', 'species_label_project_id')
    op.add_column('specieslabel', sa.Column('label_studio_project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_specieslabel_label_studio_project_id'), 'specieslabel', ['label_studio_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specieslabel_label_studio_project_id'), table_name='specieslabel')
    op.drop_column('specieslabel', 'label_studio_project_id')
    op.add_column('dive', sa.Column('species_label_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
