"""update laser calibration with additional properties

Revision ID: 0ab61944e24c
Revises: d4b600fc7f4f
Create Date: 2025-11-24 20:17:03.839444

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab61944e24c'
down_revision: Union[str, Sequence[str], None] = 'd4b600fc7f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dive_laser_calibration_id_fkey'), 'dive', type_='foreignkey')
    op.drop_column('dive', 'laser_calibration_id')
    op.add_column('lasercalibration', sa.Column('laser_position', sa.JSON(), nullable=True))
    op.add_column('lasercalibration', sa.Column('laser_axis', sa.JSON(), nullable=True))
    op.add_column('lasercalibration', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lasercalibration', sa.Column('dive_id', sa.Integer(), nullable=True))
    op.add_column('lasercalibration', sa.Column('camera_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lasercalibration', 'dive', ['dive_id'], ['id'])
    op.create_foreign_key(None, 'lasercalibration', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lasercalibration', type_='foreignkey')
    op.drop_constraint(None, 'lasercalibration', type_='foreignkey')
    op.drop_column('lasercalibration', 'camera_id')
    op.drop_column('lasercalibration', 'dive_id')
    op.drop_column('lasercalibration', 'created_at')
    op.drop_column('lasercalibration', 'laser_axis')
    op.drop_column('lasercalibration', 'laser_position')
    op.add_column('dive', sa.Column('laser_calibration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('dive_laser_calibration_id_fkey'), 'dive', 'lasercalibration', ['laser_calibration_id'], ['id'])
    # ### end Alembic commands ###
