"""add source to dive frame cluster

Revision ID: 0be8cff03ac3
Revises: 0771a69e2895
Create Date: 2025-11-16 20:39:28.693028

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be8cff03ac3'
down_revision: Union[str, Sequence[str], None] = '0771a69e2895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE datasource AS ENUM ('PREDICTION', 'LABEL_STUDIO')")
    op.add_column('diveframecluster', sa.Column('data_source', sa.Enum('PREDICTION', 'LABEL_STUDIO', name='datasource'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diveframecluster', 'data_source')
    op.execute("DROP TYPE datasource")
    # ### end Alembic commands ###
