"""baseline

Revision ID: 1e74b86658e1
Revises: 
Create Date: 2025-09-03 11:53:16.646930

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e74b86658e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
