"""rename dive slate labels to match all other labels

Revision ID: 1f4ea39106fc
Revises: b706f08c7d14
Create Date: 2025-11-23 17:22:14.912104

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f4ea39106fc"
down_revision: Union[str, Sequence[str], None] = "b706f08c7d14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diveslatelabel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label_studio_task_id", sa.Integer(), nullable=True),
        sa.Column("label_studio_project_id", sa.Integer(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("label_studio_json", sa.JSON(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diveslatelabel_label_studio_project_id"),
        "diveslatelabel",
        ["label_studio_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diveslatelabel_label_studio_task_id"),
        "diveslatelabel",
        ["label_studio_task_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_diveslatelabels_label_studio_project_id"), table_name="diveslatelabels"
    )
    op.drop_index(
        op.f("ix_diveslatelabels_label_studio_task_id"), table_name="diveslatelabels"
    )
    op.drop_table("diveslatelabels")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diveslatelabels",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "label_studio_task_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "label_studio_project_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "label_studio_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name=op.f("diveslatelabels_image_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("diveslatelabels_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("diveslatelabels_pkey")),
    )
    op.create_index(
        op.f("ix_diveslatelabels_label_studio_task_id"),
        "diveslatelabels",
        ["label_studio_task_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_diveslatelabels_label_studio_project_id"),
        "diveslatelabels",
        ["label_studio_project_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_diveslatelabel_label_studio_task_id"), table_name="diveslatelabel"
    )
    op.drop_index(
        op.f("ix_diveslatelabel_label_studio_project_id"), table_name="diveslatelabel"
    )
    op.drop_table("diveslatelabel")
    # ### end Alembic commands ###
