"""remove shadowed json property

Revision ID: 312a24726f7a
Revises: e679e406f8bf
Create Date: 2025-09-05 20:03:56.502648

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '312a24726f7a'
down_revision: Union[str, Sequence[str], None] = 'e679e406f8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headtaillabel', 'json')
    op.drop_column('laserlabel', 'json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserlabel', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('headtaillabel', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
