"""add camera calibration table.

Revision ID: 3217df630d03
Revises: 1b704b53212f
Create Date: 2025-10-14 22:05:39.896432

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3217df630d03'
down_revision: Union[str, Sequence[str], None] = '1b704b53212f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameracalibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibration_type', sa.Enum('CAMERA_INTRINSICS', name='cameracalibrationtype'), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dive', 'priority',
               existing_type=postgresql.ENUM('LOW', 'HIGH', name='priority'),
               nullable=True)
    op.drop_index(op.f('ix_dive_priority'), table_name='dive')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_dive_priority'), 'dive', ['priority'], unique=False)
    op.alter_column('dive', 'priority',
               existing_type=postgresql.ENUM('LOW', 'HIGH', name='priority'),
               nullable=False)
    op.drop_table('cameracalibration')
    # ### end Alembic commands ###
