"""add updated date and json to label studio labels

Revision ID: 3770d7474078
Revises: 2fcaca861c32
Create Date: 2025-09-03 13:35:10.474772

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3770d7474078'
down_revision: Union[str, Sequence[str], None] = '2fcaca861c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent against `SQLModel.metadata.create_all`: the FastAPI
    lifespan runs `create_all` before alembic upgrade, so on a
    fresh-bootstrap deploy these columns already exist by the time
    the migration runs (the SQLModel ORM defines them). Skip the DDL
    for any column that's already present. Same fix pattern as
    `299428e39cb9_add_label_studio_sync_cursor.py`.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    headtail_cols = {c["name"] for c in inspector.get_columns("headtaillabel")}
    if "updated_at" not in headtail_cols:
        op.add_column('headtaillabel', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    if "json" not in headtail_cols:
        op.add_column('headtaillabel', sa.Column('json', sa.JSON(), nullable=True))

    laser_cols = {c["name"] for c in inspector.get_columns("laserlabel")}
    if "updated_at" not in laser_cols:
        op.add_column('laserlabel', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    if "json" not in laser_cols:
        op.add_column('laserlabel', sa.Column('json', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laserlabel', 'json')
    op.drop_column('laserlabel', 'updated_at')
    op.drop_column('headtaillabel', 'json')
    op.drop_column('headtaillabel', 'updated_at')
    # ### end Alembic commands ###
