"""renamed laser calibration to laser extrinsics

Revision ID: 426fa1cdedec
Revises: 0ab61944e24c
Create Date: 2025-11-24 20:21:14.708059

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '426fa1cdedec'
down_revision: Union[str, Sequence[str], None] = '0ab61944e24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laserextrinsics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laser_position', sa.JSON(), nullable=True),
    sa.Column('laser_axis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lasercalibration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lasercalibration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('laser_position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('laser_axis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dive_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], name=op.f('lasercalibration_camera_id_fkey')),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.id'], name=op.f('lasercalibration_dive_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lasercalibration_pkey'))
    )
    op.drop_table('laserextrinsics')
    # ### end Alembic commands ###
