"""add image url to species label

Revision ID: 4cf2f0d88592
Revises: cda3ad75a927
Create Date: 2025-10-15 11:08:08.347390

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cf2f0d88592"
down_revision: Union[str, Sequence[str], None] = "cda3ad75a927"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specieslabel",
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specieslabel", "image_url")
    # ### end Alembic commands ###
