"""update label studio species model to better match label studio

Revision ID: 5d89e619453e
Revises: 6d704a322e1f
Create Date: 2025-11-17 23:30:24.411959

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d89e619453e"
down_revision: Union[str, Sequence[str], None] = "6d704a322e1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specieslabel",
        sa.Column("grouping", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("specieslabel", "part_of_previous_group")
    op.drop_column("specieslabel", "not_part_of_current_group")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specieslabel",
        sa.Column(
            "not_part_of_current_group",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "specieslabel",
        sa.Column(
            "part_of_previous_group", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("specieslabel", "grouping")
    # ### end Alembic commands ###
