"""add dive slate to dive

Revision ID: 65170bdda5ed
Revises: c6850b78f9f1
Create Date: 2025-09-05 11:27:14.499920

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65170bdda5ed"
down_revision: Union[str, Sequence[str], None] = "c6850b78f9f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diveslate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_diveslate_name"), "diveslate", ["name"], unique=True)
    op.create_index(op.f("ix_diveslate_path"), "diveslate", ["path"], unique=True)
    op.add_column("dive", sa.Column("dive_slate_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "dive", "diveslate", ["dive_slate_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dive", type_="foreignkey")
    op.drop_column("dive", "dive_slate_id")
    op.drop_index(op.f("ix_diveslate_path"), table_name="diveslate")
    op.drop_index(op.f("ix_diveslate_name"), table_name="diveslate")
    op.drop_table("diveslate")
    # ### end Alembic commands ###
