"""add missing properties for species label

Revision ID: 6d704a322e1f
Revises: d66708f6720c
Create Date: 2025-11-17 23:13:50.324458

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d704a322e1f"
down_revision: Union[str, Sequence[str], None] = "d66708f6720c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specieslabel", sa.Column("part_of_previous_group", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "specieslabel",
        sa.Column("not_part_of_current_group", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "specieslabel",
        sa.Column("top_three_photos_of_group", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "specieslabel", sa.Column("slate_upside_down", sa.Boolean(), nullable=True)
    )
    op.add_column("specieslabel", sa.Column("laser_x", sa.Float(), nullable=True))
    op.add_column("specieslabel", sa.Column("laser_y", sa.Float(), nullable=True))
    op.add_column(
        "specieslabel",
        sa.Column("laser_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "specieslabel",
        sa.Column(
            "content_of_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "specieslabel",
        sa.Column(
            "fish_measurable_category",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "specieslabel",
        sa.Column(
            "fish_angle_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "specieslabel",
        sa.Column(
            "fish_curved_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specieslabel", "fish_curved_category")
    op.drop_column("specieslabel", "fish_angle_category")
    op.drop_column("specieslabel", "fish_measurable_category")
    op.drop_column("specieslabel", "content_of_image")
    op.drop_column("specieslabel", "laser_label")
    op.drop_column("specieslabel", "laser_y")
    op.drop_column("specieslabel", "laser_x")
    op.drop_column("specieslabel", "slate_upside_down")
    op.drop_column("specieslabel", "top_three_photos_of_group")
    op.drop_column("specieslabel", "not_part_of_current_group")
    op.drop_column("specieslabel", "part_of_previous_group")
    # ### end Alembic commands ###
