"""add points json to sql server

Revision ID: 711bd7660a82
Revises: ac4a4228768c
Create Date: 2025-11-23 15:22:39.955752

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711bd7660a82'
down_revision: Union[str, Sequence[str], None] = 'ac4a4228768c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveslate', sa.Column('points_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diveslate', 'points_json')
    # ### end Alembic commands ###
