"""add name to dive

Revision ID: 72af359854fa
Revises: 312a24726f7a
Create Date: 2025-09-14 22:16:02.349884

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72af359854fa"
down_revision: Union[str, Sequence[str], None] = "312a24726f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dive", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_dive_name"), "dive", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dive_name"), table_name="dive")
    op.drop_column("dive", "name")
    # ### end Alembic commands ###
