"""add fish id to dive frame cluster

Revision ID: 73e02848540f
Revises: ed4a696f435a
Create Date: 2025-11-25 19:15:44.675829

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e02848540f'
down_revision: Union[str, Sequence[str], None] = 'ed4a696f435a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveframecluster', sa.Column('fish_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diveframecluster', 'fish', ['fish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diveframecluster', type_='foreignkey')
    op.drop_column('diveframecluster', 'fish_id')
    # ### end Alembic commands ###
