"""add project id to headtail label

Revision ID: 788e855b5474
Revises: b3a78115ba3d
Create Date: 2025-11-22 19:28:04.468192

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788e855b5474'
down_revision: Union[str, Sequence[str], None] = 'b3a78115ba3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headtaillabel', sa.Column('label_studio_project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_headtaillabel_label_studio_project_id'), 'headtaillabel', ['label_studio_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headtaillabel_label_studio_project_id'), table_name='headtaillabel')
    op.drop_column('headtaillabel', 'label_studio_project_id')
    # ### end Alembic commands ###
