"""update to include camera intrinsics.

Revision ID: 9e0d4544eedf
Revises: 3217df630d03
Create Date: 2025-10-14 22:15:06.492490

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e0d4544eedf'
down_revision: Union[str, Sequence[str], None] = '3217df630d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameraintrinsics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_matrix', sa.JSON(), nullable=True),
    sa.Column('distortion_coefficients', sa.JSON(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cameracalibration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameracalibration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calibration_type', postgresql.ENUM('CAMERA_INTRINSICS', name='cameracalibrationtype'), autoincrement=False, nullable=True),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], name=op.f('cameracalibration_camera_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cameracalibration_pkey'))
    )
    op.drop_table('cameraintrinsics')
    # ### end Alembic commands ###
