"""add dpi property to dive slate

Revision ID: ac4a4228768c
Revises: 06886d4ca175
Create Date: 2025-11-23 13:35:17.841852

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4a4228768c'
down_revision: Union[str, Sequence[str], None] = '06886d4ca175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveslate', sa.Column('dpi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diveslate', 'dpi')
    # ### end Alembic commands ###
