"""added superseded and project id to laser label

Revision ID: b3a78115ba3d
Revises: 5d89e619453e
Create Date: 2025-11-22 09:34:00.074467

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a78115ba3d'
down_revision: Union[str, Sequence[str], None] = '5d89e619453e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserlabel', sa.Column('label_studio_project_id', sa.Integer(), nullable=True))
    op.add_column('laserlabel', sa.Column('superseded', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_laserlabel_label_studio_project_id'), 'laserlabel', ['label_studio_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laserlabel_label_studio_project_id'), table_name='laserlabel')
    op.drop_column('laserlabel', 'superseded')
    op.drop_column('laserlabel', 'label_studio_project_id')
    # ### end Alembic commands ###
