"""rename slate labels to dive slate labels

Revision ID: b706f08c7d14
Revises: ff17822ba47e
Create Date: 2025-11-23 17:13:55.085780

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b706f08c7d14'
down_revision: Union[str, Sequence[str], None] = 'ff17822ba47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diveslatelabels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_studio_task_id', sa.Integer(), nullable=True),
    sa.Column('label_studio_project_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('label_studio_json', sa.JSON(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diveslatelabels_label_studio_project_id'), 'diveslatelabels', ['label_studio_project_id'], unique=False)
    op.create_index(op.f('ix_diveslatelabels_label_studio_task_id'), 'diveslatelabels', ['label_studio_task_id'], unique=True)
    op.drop_index(op.f('ix_slatelabels_label_studio_project_id'), table_name='slatelabels')
    op.drop_index(op.f('ix_slatelabels_label_studio_task_id'), table_name='slatelabels')
    op.drop_table('slatelabels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slatelabels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label_studio_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label_studio_project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('label_studio_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('slatelabels_image_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('slatelabels_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('slatelabels_pkey'))
    )
    op.create_index(op.f('ix_slatelabels_label_studio_task_id'), 'slatelabels', ['label_studio_task_id'], unique=True)
    op.create_index(op.f('ix_slatelabels_label_studio_project_id'), 'slatelabels', ['label_studio_project_id'], unique=False)
    op.drop_index(op.f('ix_diveslatelabels_label_studio_task_id'), table_name='diveslatelabels')
    op.drop_index(op.f('ix_diveslatelabels_label_studio_project_id'), table_name='diveslatelabels')
    op.drop_table('diveslatelabels')
    # ### end Alembic commands ###
