"""add completed column to label studio labels

Revision ID: c6850b78f9f1
Revises: c97e22fa9be0
Create Date: 2025-09-03 17:32:49.809390

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6850b78f9f1"
down_revision: Union[str, Sequence[str], None] = "c97e22fa9be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("headtaillabel", sa.Column("completed", sa.Boolean(), nullable=True))
    op.add_column("laserlabel", sa.Column("completed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("laserlabel", "completed")
    op.drop_column("headtaillabel", "completed")
    # ### end Alembic commands ###
