"""rename points_json to reference_points

Revision ID: c9bcc28fa541
Revises: b29f595da116
Create Date: 2025-11-23 16:04:13.869174

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9bcc28fa541'
down_revision: Union[str, Sequence[str], None] = 'b29f595da116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveslate', sa.Column('reference_points', sa.JSON(), nullable=True))
    op.drop_column('diveslate', 'points_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveslate', sa.Column('points_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('diveslate', 'reference_points')
    # ### end Alembic commands ###
