"""add species label to database

Revision ID: cda3ad75a927
Revises: 9e0d4544eedf
Create Date: 2025-10-15 10:50:44.960067

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda3ad75a927'
down_revision: Union[str, Sequence[str], None] = '9e0d4544eedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specieslabel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_studio_task_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('label_studio_json', sa.JSON(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specieslabel_label_studio_task_id'), 'specieslabel', ['label_studio_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specieslabel_label_studio_task_id'), table_name='specieslabel')
    op.drop_table('specieslabel')
    # ### end Alembic commands ###
