"""add foreing key for laser calibration to dive.

Revision ID: d4b600fc7f4f
Revises: b7bbd9423b29
Create Date: 2025-11-23 20:47:04.644867

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b600fc7f4f'
down_revision: Union[str, Sequence[str], None] = 'b7bbd9423b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive', sa.Column('laser_calibration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dive', 'lasercalibration', ['laser_calibration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dive', type_='foreignkey')
    op.drop_column('dive', 'laser_calibration_id')
    # ### end Alembic commands ###
