"""add updated time to dive frame cluster

Revision ID: d66708f6720c
Revises: 0be8cff03ac3
Create Date: 2025-11-16 20:42:01.076205

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66708f6720c'
down_revision: Union[str, Sequence[str], None] = '0be8cff03ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diveframecluster', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diveframecluster', 'updated_at')
    # ### end Alembic commands ###
