"""add unique constraints to the label

Revision ID: dae6f36a7ebc
Revises: 73e02848540f
Create Date: 2026-02-24 08:31:47.668026

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae6f36a7ebc'
down_revision: Union[str, Sequence[str], None] = '73e02848540f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_dive_slate_image_project', 'diveslatelabel', ['image_id', 'label_studio_project_id'])
    op.create_unique_constraint('uq_headtail_image_project', 'headtaillabel', ['image_id', 'label_studio_project_id'])
    op.create_unique_constraint('uq_laser_image_project', 'laserlabel', ['image_id', 'label_studio_project_id'])
    op.create_unique_constraint('uq_species_image_project', 'specieslabel', ['image_id', 'label_studio_project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_species_image_project', 'specieslabel', type_='unique')
    op.drop_constraint('uq_laser_image_project', 'laserlabel', type_='unique')
    op.drop_constraint('uq_headtail_image_project', 'headtaillabel', type_='unique')
    op.drop_constraint('uq_dive_slate_image_project', 'diveslatelabel', type_='unique')
    # ### end Alembic commands ###
