"""add unique constraints to users and camera

Revision ID: e1fc97743091
Revises: dae6f36a7ebc
Create Date: 2026-02-24 09:50:08.273321

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fc97743091'
down_revision: Union[str, Sequence[str], None] = 'dae6f36a7ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_camera_name', 'camera', ['name'])
    op.create_unique_constraint('uq_camera_serial_number', 'camera', ['serial_number'])
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.create_unique_constraint('uq_user_label_studio_id', 'user', ['label_studio_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_label_studio_id', 'user', type_='unique')
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.drop_constraint('uq_camera_serial_number', 'camera', type_='unique')
    op.drop_constraint('uq_camera_name', 'camera', type_='unique')
    # ### end Alembic commands ###
