"""migrate to new json property

Revision ID: e679e406f8bf
Revises: f1dfeee32336
Create Date: 2025-09-05 19:46:43.876021

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e679e406f8bf'
down_revision: Union[str, Sequence[str], None] = 'f1dfeee32336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headtaillabel', sa.Column('label_studio_json', sa.JSON(), nullable=True))
    op.add_column('laserlabel', sa.Column('label_studio_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laserlabel', 'label_studio_json')
    op.drop_column('headtaillabel', 'label_studio_json')
    # ### end Alembic commands ###
