"""add species, fish, and measurement

Revision ID: ed4a696f435a
Revises: 426fa1cdedec
Create Date: 2025-11-25 18:51:24.421498

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed4a696f435a'
down_revision: Union[str, Sequence[str], None] = '426fa1cdedec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=False)
    op.create_table('fish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    op.drop_table('fish')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
