"""add flip dive slate

Revision ID: f700e0bd3e0e
Revises: 65170bdda5ed
Create Date: 2025-09-05 11:47:25.582777

"""
# pylint: skip-file

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f700e0bd3e0e'
down_revision: Union[str, Sequence[str], None] = '65170bdda5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive', sa.Column('flip_dive_slate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive', 'flip_dive_slate')
    # ### end Alembic commands ###
