"""add slate labels

Revision ID: ff17822ba47e
Revises: c9bcc28fa541
Create Date: 2025-11-23 17:10:30.746896

"""

# pylint: skip-file

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff17822ba47e"
down_revision: Union[str, Sequence[str], None] = "c9bcc28fa541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slatelabels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label_studio_task_id", sa.Integer(), nullable=True),
        sa.Column("label_studio_project_id", sa.Integer(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("label_studio_json", sa.JSON(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_slatelabels_label_studio_project_id"),
        "slatelabels",
        ["label_studio_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slatelabels_label_studio_task_id"),
        "slatelabels",
        ["label_studio_task_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slatelabels_label_studio_task_id"), table_name="slatelabels")
    op.drop_index(
        op.f("ix_slatelabels_label_studio_project_id"), table_name="slatelabels"
    )
    op.drop_table("slatelabels")
    # ### end Alembic commands ###
