FROM ghcr.io/ucsd-e4e/fishsense-lite:cpu

SHELL ["/bin/bash", "-c"]

RUN pip install pipx
RUN pipx ensurepath

RUN . ${HOME}/.cargo/env && pipx install git+https://github.com/UCSD-E4E/fishsense-lite.git

CMD ["/bin/bash"]
