@startuml Calibrate Lens and Laser
actor Actor
participant UI
participant Backend
database Database

Actor -> UI: Request to calibrate lens and laser
UI -> Actor: Display UI to select lens calibration RAWs
Actor -> UI: Select lens calibration RAWs
UI -> Backend: Request calibrate lens
Backend -> UI: Return lens calibration parameters

UI -> Actor: Display UI to select laser calibration RAWs
UI -> Backend: Request process and undistort RAWs
Backend -> UI: Provide undistorted and processed RAW bytes
UI -> Actor: Display UI to label laser dots
Actor -> UI: Label laser dots
UI -> Backend: Request calibrate laser
Backend -> UI: Return laser calibration parameters

UI -> Database: Request to store lens and laser calibration
UI -> Actor: Report success of laser and lens calibration
@enduml