name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-cuda:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build Base
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.base
        build-args:
          -IMAGE=nvidia/cuda:12.6.1-devel-ubuntu24.04
        tags: ghcr.io/ucsd-e4e/fishsense-lite:base-cuda
        push: false
    -
      name: Build Middle
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.mid-cuda
        tags: ghcr.io/ucsd-e4e/fishsense-lite:mid-cuda
        push: false
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile
        tags: ghcr.io/ucsd-e4e/fishsense-lite:cuda
        build-args:
          -IMAGE=ghcr.io/ucsd-e4e/fishsense-lite:mid-cuda
        push: true

  build-cpu:

    runs-on: ubuntu-latest
    
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build Base
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.base
        build-args:
          -IMAGE=ubuntu:24.04
        tags: ghcr.io/ucsd-e4e/fishsense-lite:base-cpu
        push: false
    -
      name: Build Middle
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.mid-cpu
        tags: ghcr.io/ucsd-e4e/fishsense-lite:mid-cpu
        push: false
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile
        tags: ghcr.io/ucsd-e4e/fishsense-lite:cpu
        build-args:
          -IMAGE=ghcr.io/ucsd-e4e/fishsense-lite:mid-cpu
        push: true
