name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the GPU Docker image
      run: docker build . --file docker/Dockerfile.gpu --tag fishsense-lite:gpu-$(date +%s)
