name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-gpu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the GPU Docker image
      run: docker build . --file docker/Dockerfile.gpu --tag fishsense-lite:gpu-$(date +%s) --tag fishsense-lite:gpu-latest

  build-cpu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the CPU Docker image
      run: docker build . --file docker/Dockerfile.cpu --tag fishsense-lite:cpu-$(date +%s) --tag fishsense-lite:cpu-latest
