name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-gpu:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.gpu
        tags: ghcr.io/ucsd-e4e/fishsense-lite-gpu:latest
        push: true

  build-cpu:

    runs-on: ubuntu-latest
    
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.cpu
        tags: ghcr.io/ucsd-e4e/fishsense-lite-cpu:latest
        push: true
