name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cargo install https://github.com/UCSD-E4E/pyFishSense.git
        apt update
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install --with dev
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')